services:
  - type: web
    name: ipt-group-mission-fbcs
    env: python
    region: singapore
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn school_project.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.14.3"
