# Generated by Django 6.0.3 on 2026-03-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='schedule',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
