# Generated by Django 5.2.13 on 2026-04-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_token',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
    ]
